//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаявкиНаПокупку
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗаявкиНаПокупку()
        {
            this.СоставЗаявки = new HashSet<СоставЗаявки>();
            this.СоставЗаявки1 = new HashSet<СоставЗаявки>();
        }
    
        public int ЗаявкаID { get; set; }
        public Nullable<int> ДиректорID { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Статус { get; set; }
        public Nullable<int> ПоставщикID { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Сотрудники Сотрудники1 { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Поставщики Поставщики1 { get; set; }
        public virtual СтатусыЗаявки СтатусыЗаявки { get; set; }
        public virtual СтатусыЗаявки СтатусыЗаявки1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаявки> СоставЗаявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаявки> СоставЗаявки1 { get; set; }
    }
}
