//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияВходов
    {
        public int ЛогID { get; set; }
        public Nullable<int> СотрудникID { get; set; }
        public Nullable<System.DateTime> ДатаВхода { get; set; }
        public string IPадрес { get; set; }
        public Nullable<int> Статус { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Сотрудники Сотрудники1 { get; set; }
        public virtual СтатусВхода СтатусВхода { get; set; }
        public virtual СтатусВхода СтатусВхода1 { get; set; }
    }
}
