//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставки()
        {
            this.СоставПоставки = new HashSet<СоставПоставки>();
        }
    
        public int ПоставкаID { get; set; }
        public Nullable<int> СотрудникID { get; set; }
        public Nullable<System.DateTime> ДатаПоставки { get; set; }
        public Nullable<int> ПоставщикID { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        public virtual Поставщики Поставщики1 { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Сотрудники Сотрудники1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПоставки> СоставПоставки { get; set; }
    }
}
