//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продажи()
        {
            this.СоставПродажи = new HashSet<СоставПродажи>();
            this.СоставПродажи1 = new HashSet<СоставПродажи>();
        }
    
        public int ПродажаID { get; set; }
        public Nullable<int> СотрудникID { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<int> КлиентID { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Клиенты Клиенты1 { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Сотрудники Сотрудники1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродажи> СоставПродажи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродажи> СоставПродажи1 { get; set; }
    }
}
