//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.БлокировкаПользователей = new HashSet<БлокировкаПользователей>();
            this.БлокировкаПользователей1 = new HashSet<БлокировкаПользователей>();
            this.ЗаявкиНаПокупку = new HashSet<ЗаявкиНаПокупку>();
            this.ЗаявкиНаПокупку1 = new HashSet<ЗаявкиНаПокупку>();
            this.ИзмененияЗП = new HashSet<ИзмененияЗП>();
            this.ИзмененияЗП1 = new HashSet<ИзмененияЗП>();
            this.ИсторияВходов = new HashSet<ИсторияВходов>();
            this.ИсторияВходов1 = new HashSet<ИсторияВходов>();
            this.Поставки = new HashSet<Поставки>();
            this.Поставки1 = new HashSet<Поставки>();
            this.Премии = new HashSet<Премии>();
            this.Премии1 = new HashSet<Премии>();
            this.Продажи = new HashSet<Продажи>();
            this.Продажи1 = new HashSet<Продажи>();
            this.СписаниеТоваров = new HashSet<СписаниеТоваров>();
            this.СписаниеТоваров1 = new HashSet<СписаниеТоваров>();
            this.Увольнения = new HashSet<Увольнения>();
            this.Увольнения1 = new HashSet<Увольнения>();
        }
    
        public int СотрудникID { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> ДолжностьID { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public Nullable<System.DateTime> ДатаПриема { get; set; }
        public Nullable<System.DateTime> ДатаУвольнения { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<БлокировкаПользователей> БлокировкаПользователей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<БлокировкаПользователей> БлокировкаПользователей1 { get; set; }
        public virtual Должности Должности { get; set; }
        public virtual Должности Должности1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаявкиНаПокупку> ЗаявкиНаПокупку { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаявкиНаПокупку> ЗаявкиНаПокупку1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИзмененияЗП> ИзмененияЗП { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИзмененияЗП> ИзмененияЗП1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИсторияВходов> ИсторияВходов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИсторияВходов> ИсторияВходов1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки> Поставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки> Поставки1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Премии> Премии { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Премии> Премии1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписаниеТоваров> СписаниеТоваров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписаниеТоваров> СписаниеТоваров1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Увольнения> Увольнения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Увольнения> Увольнения1 { get; set; }
    }
}
