//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаявки
    {
        public int ЗаявкиID { get; set; }
        public int ТоварID { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual ЗаявкиНаПокупку ЗаявкиНаПокупку { get; set; }
        public virtual ЗаявкиНаПокупку ЗаявкиНаПокупку1 { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
