//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.СоставЗаявки = new HashSet<СоставЗаявки>();
            this.СоставПоставки = new HashSet<СоставПоставки>();
            this.СоставПоставки1 = new HashSet<СоставПоставки>();
            this.СоставПродажи = new HashSet<СоставПродажи>();
            this.СписаниеТоваров = new HashSet<СписаниеТоваров>();
        }
    
        public int ТоварID { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<System.DateTime> СрокГодности { get; set; }
        public Nullable<int> ТипТовара { get; set; }
        public Nullable<int> ПоставщикID { get; set; }
        public Nullable<int> КатегорияID { get; set; }
    
        public virtual КатегорииТоваров КатегорииТоваров { get; set; }
        public virtual КатегорииТоваров КатегорииТоваров1 { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Поставщики Поставщики1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаявки> СоставЗаявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПоставки> СоставПоставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПоставки> СоставПоставки1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродажи> СоставПродажи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписаниеТоваров> СписаниеТоваров { get; set; }
        public virtual ТипТовара ТипТовара1 { get; set; }
        public virtual ТипТовара ТипТовара2 { get; set; }
    }
}
